# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    #cp known_hosts.github /root/.ssh/known_hosts
    ssh-keyscan -p 7999

    /root/.ssh/known_hosts

    ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:kralagonda/cloudbuild
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/praxis-water-391016/secrets/kr_cloudbuild/versions/latest
    env: 'SSH_KEY'

  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.7'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
       if [ -d "cloudbuild/$BRANCH_NAME/" ]; then
          cd environments/$BRANCH_NAME
          terraform plan
        else
         for dir in cloudbuild/*/
         do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../
        done
       fi 