# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    #cp known_hosts.github /root/.ssh/known_hosts
    ssh-keyscan -p 7999

    /root/.ssh/known_hosts

    ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:kralagonda/cloudbuild
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/praxis-water-391016/secrets/kr_cloudbuild/versions/latest
    env: 'SSH_KEY'


  steps:

  - name: 'hashicorp/terraform:1.0.7'

    dir: workingdir/cloudbuild/bucket

    args:

      - '-c'

      - |

        terraform init

    id: terraform init

    entrypoint: sh

  - name: 'hashicorp/terraform:1.0.7'

    dir: workingdir/cloudbuild/bucket

    args:

      - '-c'

      - |

        terraform fmt

    id: terraform fmt

    entrypoint: sh

  - name: 'hashicorp/terraform:1.0.7'

    dir: workingdir/cloudbuild/bucket

    args:

      - '-c'

      - |

        terraform validate

    id: terraform validate

    entrypoint: sh

  - name: 'hashicorp/terraform:1.0.7'

    dir: workingdir/cloudbuild/bucket

    args:

      - '-c'

      - |

        terraform plan

    id: terraform plan

    entrypoint: sh

  - name: 'hashicorp/terraform:1.0.7'

    dir: workingdir/cloudbuild/bucket

    args:

      - '-c'

      - |

        terraform apply -input=false -auto-approve

    id: terraform apply

    entrypoint: sh

logsBucket: 'gs://praxis-water-391016-tfstate'

options:

  logging: GCS_ONLY
