substitution:

#_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY/terraform
_DEFAULT_REGION: northamerica-northeast1-a

_PROJECT_ID: praxis-water-391016
_REPO_URL: https://github.com/kralagonda/cloudbuild.git
_TF_SA_EMAIL: testbuild@praxis-water-391016.iam.gserviceaccount.com





# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    #cp known_hosts.github /root/.ssh/known_hosts
    ssh-keyscan -p 7999

    /root/.ssh/known_hosts

    ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash 
  args:
  - clone
  - --recurse-submodules
  - git@github.com:kralagonda/cloudbuild
  volumes:
  - name: 'ssh'
    path: /root/.ssh

  availableSecrets:
    secretManager:
    - versionName: projects/praxis-water-391016/secrets/kr_cloudbuild/versions/latest
      env: 'SSH_KEY'

step:
- id: 'setup'
  name: $_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_URL/terraform
  entrypoint: /bin/bash
  args:
    - "-eEuo"
    - "pipefail"
    - -c
    - |
      tf_sa_email=${_TF_SA_EMAIL}
      if [[ -n ${tf_sa_email} ]]; then
        echo "Setting up gcloud for impersonation"
        gcloud config set auth/impersonate_service_account $tf_sa_email
      fi

- id: 'tf-plan'
  name: $_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_URL/terraform
  entrypoint: /bin/bash
  args:
    - "-eEuo"
    - "pipefail"
    - -c
    - |
       
